// flow-typed signature: a2c88e84e3498bba7b7a1c2f367c3d1a
// flow-typed version: <<STUB>>/babel-plugin-s2s-action-types_v^0.4.9/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-s2s-action-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-s2s-action-types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-s2s-action-types/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-s2s-action-types/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-s2s-action-types/lib/index'>;
}
