// flow-typed signature: a306a0195445b93015096b599fb952e4
// flow-typed version: <<STUB>>/babel-plugin-s2s-state-root_v^0.2.10/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-s2s-state-root'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-s2s-state-root' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-s2s-state-root/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-s2s-state-root/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-s2s-state-root/lib/index'>;
}
