// flow-typed signature: de5c63d649d01f7e86f516097e81278b
// flow-typed version: <<STUB>>/binary_v^0.3.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'binary'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'binary' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'binary/example/buf' {
  declare module.exports: any;
}

declare module 'binary/example/parse' {
  declare module.exports: any;
}

declare module 'binary/example/stream' {
  declare module.exports: any;
}

declare module 'binary/lib/vars' {
  declare module.exports: any;
}

declare module 'binary/perf/loop' {
  declare module.exports: any;
}

declare module 'binary/perf/small' {
  declare module.exports: any;
}

declare module 'binary/test/bu' {
  declare module.exports: any;
}

declare module 'binary/test/deferred' {
  declare module.exports: any;
}

declare module 'binary/test/dots' {
  declare module.exports: any;
}

declare module 'binary/test/eof' {
  declare module.exports: any;
}

declare module 'binary/test/flush' {
  declare module.exports: any;
}

declare module 'binary/test/from_buffer' {
  declare module.exports: any;
}

declare module 'binary/test/get_buffer' {
  declare module.exports: any;
}

declare module 'binary/test/immediate' {
  declare module.exports: any;
}

declare module 'binary/test/interval' {
  declare module.exports: any;
}

declare module 'binary/test/into_buffer' {
  declare module.exports: any;
}

declare module 'binary/test/into_stream' {
  declare module.exports: any;
}

declare module 'binary/test/loop_scan' {
  declare module.exports: any;
}

declare module 'binary/test/loop' {
  declare module.exports: any;
}

declare module 'binary/test/lu' {
  declare module.exports: any;
}

declare module 'binary/test/negbs' {
  declare module.exports: any;
}

declare module 'binary/test/negls' {
  declare module.exports: any;
}

declare module 'binary/test/nested' {
  declare module.exports: any;
}

declare module 'binary/test/not_enough_buf' {
  declare module.exports: any;
}

declare module 'binary/test/not_enough_parse' {
  declare module.exports: any;
}

declare module 'binary/test/parse' {
  declare module.exports: any;
}

declare module 'binary/test/peek' {
  declare module.exports: any;
}

declare module 'binary/test/pipe' {
  declare module.exports: any;
}

declare module 'binary/test/posbs' {
  declare module.exports: any;
}

declare module 'binary/test/posls' {
  declare module.exports: any;
}

declare module 'binary/test/scan_buf_null' {
  declare module.exports: any;
}

declare module 'binary/test/scan_buf' {
  declare module.exports: any;
}

declare module 'binary/test/scan' {
  declare module.exports: any;
}

declare module 'binary/test/skip' {
  declare module.exports: any;
}

declare module 'binary/test/split' {
  declare module.exports: any;
}

// Filename aliases
declare module 'binary/example/buf.js' {
  declare module.exports: $Exports<'binary/example/buf'>;
}
declare module 'binary/example/parse.js' {
  declare module.exports: $Exports<'binary/example/parse'>;
}
declare module 'binary/example/stream.js' {
  declare module.exports: $Exports<'binary/example/stream'>;
}
declare module 'binary/index' {
  declare module.exports: $Exports<'binary'>;
}
declare module 'binary/index.js' {
  declare module.exports: $Exports<'binary'>;
}
declare module 'binary/lib/vars.js' {
  declare module.exports: $Exports<'binary/lib/vars'>;
}
declare module 'binary/perf/loop.js' {
  declare module.exports: $Exports<'binary/perf/loop'>;
}
declare module 'binary/perf/small.js' {
  declare module.exports: $Exports<'binary/perf/small'>;
}
declare module 'binary/test/bu.js' {
  declare module.exports: $Exports<'binary/test/bu'>;
}
declare module 'binary/test/deferred.js' {
  declare module.exports: $Exports<'binary/test/deferred'>;
}
declare module 'binary/test/dots.js' {
  declare module.exports: $Exports<'binary/test/dots'>;
}
declare module 'binary/test/eof.js' {
  declare module.exports: $Exports<'binary/test/eof'>;
}
declare module 'binary/test/flush.js' {
  declare module.exports: $Exports<'binary/test/flush'>;
}
declare module 'binary/test/from_buffer.js' {
  declare module.exports: $Exports<'binary/test/from_buffer'>;
}
declare module 'binary/test/get_buffer.js' {
  declare module.exports: $Exports<'binary/test/get_buffer'>;
}
declare module 'binary/test/immediate.js' {
  declare module.exports: $Exports<'binary/test/immediate'>;
}
declare module 'binary/test/interval.js' {
  declare module.exports: $Exports<'binary/test/interval'>;
}
declare module 'binary/test/into_buffer.js' {
  declare module.exports: $Exports<'binary/test/into_buffer'>;
}
declare module 'binary/test/into_stream.js' {
  declare module.exports: $Exports<'binary/test/into_stream'>;
}
declare module 'binary/test/loop_scan.js' {
  declare module.exports: $Exports<'binary/test/loop_scan'>;
}
declare module 'binary/test/loop.js' {
  declare module.exports: $Exports<'binary/test/loop'>;
}
declare module 'binary/test/lu.js' {
  declare module.exports: $Exports<'binary/test/lu'>;
}
declare module 'binary/test/negbs.js' {
  declare module.exports: $Exports<'binary/test/negbs'>;
}
declare module 'binary/test/negls.js' {
  declare module.exports: $Exports<'binary/test/negls'>;
}
declare module 'binary/test/nested.js' {
  declare module.exports: $Exports<'binary/test/nested'>;
}
declare module 'binary/test/not_enough_buf.js' {
  declare module.exports: $Exports<'binary/test/not_enough_buf'>;
}
declare module 'binary/test/not_enough_parse.js' {
  declare module.exports: $Exports<'binary/test/not_enough_parse'>;
}
declare module 'binary/test/parse.js' {
  declare module.exports: $Exports<'binary/test/parse'>;
}
declare module 'binary/test/peek.js' {
  declare module.exports: $Exports<'binary/test/peek'>;
}
declare module 'binary/test/pipe.js' {
  declare module.exports: $Exports<'binary/test/pipe'>;
}
declare module 'binary/test/posbs.js' {
  declare module.exports: $Exports<'binary/test/posbs'>;
}
declare module 'binary/test/posls.js' {
  declare module.exports: $Exports<'binary/test/posls'>;
}
declare module 'binary/test/scan_buf_null.js' {
  declare module.exports: $Exports<'binary/test/scan_buf_null'>;
}
declare module 'binary/test/scan_buf.js' {
  declare module.exports: $Exports<'binary/test/scan_buf'>;
}
declare module 'binary/test/scan.js' {
  declare module.exports: $Exports<'binary/test/scan'>;
}
declare module 'binary/test/skip.js' {
  declare module.exports: $Exports<'binary/test/skip'>;
}
declare module 'binary/test/split.js' {
  declare module.exports: $Exports<'binary/test/split'>;
}
