// flow-typed signature: 273cf5f74729dc0dab3b4cabc840b1a4
// flow-typed version: <<STUB>>/react-scroll-to-component_v^1.0.2/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-scroll-to-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-scroll-to-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-scroll-to-component/docs/static/js/main.18019188' {
  declare module.exports: any;
}

declare module 'react-scroll-to-component/example/src/App' {
  declare module.exports: any;
}

declare module 'react-scroll-to-component/example/src/App.test' {
  declare module.exports: any;
}

declare module 'react-scroll-to-component/example/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-scroll-to-component/docs/static/js/main.18019188.js' {
  declare module.exports: $Exports<'react-scroll-to-component/docs/static/js/main.18019188'>;
}
declare module 'react-scroll-to-component/example/src/App.js' {
  declare module.exports: $Exports<'react-scroll-to-component/example/src/App'>;
}
declare module 'react-scroll-to-component/example/src/App.test.js' {
  declare module.exports: $Exports<'react-scroll-to-component/example/src/App.test'>;
}
declare module 'react-scroll-to-component/example/src/index.js' {
  declare module.exports: $Exports<'react-scroll-to-component/example/src/index'>;
}
declare module 'react-scroll-to-component/index' {
  declare module.exports: $Exports<'react-scroll-to-component'>;
}
declare module 'react-scroll-to-component/index.js' {
  declare module.exports: $Exports<'react-scroll-to-component'>;
}
