// flow-typed signature: 100966a4b3473405e53daa96bbdccf62
// flow-typed version: <<STUB>>/three-orbit-controls_v^82.1.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'three-orbit-controls'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'three-orbit-controls' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'three-orbit-controls/index' {
  declare module.exports: $Exports<'three-orbit-controls'>;
}
declare module 'three-orbit-controls/index.js' {
  declare module.exports: $Exports<'three-orbit-controls'>;
}
