// flow-typed signature: c80eafeecc8c75f03c87f3366cf12171
// flow-typed version: <<STUB>>/@nivo/bullet_v^0.49.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nivo/bullet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nivo/bullet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nivo/bullet/cjs/nivo-bullet' {
  declare module.exports: any;
}

declare module '@nivo/bullet/umd/nivo-bullet' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nivo/bullet/cjs/nivo-bullet.js' {
  declare module.exports: $Exports<'@nivo/bullet/cjs/nivo-bullet'>;
}
declare module '@nivo/bullet/index' {
  declare module.exports: $Exports<'@nivo/bullet'>;
}
declare module '@nivo/bullet/index.js' {
  declare module.exports: $Exports<'@nivo/bullet'>;
}
declare module '@nivo/bullet/umd/nivo-bullet.js' {
  declare module.exports: $Exports<'@nivo/bullet/umd/nivo-bullet'>;
}
