// flow-typed signature: 707aec38928cad1f20733112eb494137
// flow-typed version: <<STUB>>/@nivo/heatmap_v^0.49.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nivo/heatmap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nivo/heatmap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nivo/heatmap/cjs/nivo-heatmap' {
  declare module.exports: any;
}

declare module '@nivo/heatmap/umd/nivo-heatmap' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nivo/heatmap/cjs/nivo-heatmap.js' {
  declare module.exports: $Exports<'@nivo/heatmap/cjs/nivo-heatmap'>;
}
declare module '@nivo/heatmap/index' {
  declare module.exports: $Exports<'@nivo/heatmap'>;
}
declare module '@nivo/heatmap/index.js' {
  declare module.exports: $Exports<'@nivo/heatmap'>;
}
declare module '@nivo/heatmap/umd/nivo-heatmap.js' {
  declare module.exports: $Exports<'@nivo/heatmap/umd/nivo-heatmap'>;
}
